[supervisord]
nodaemon=true
user=root
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1920x1080x24 -nolisten tcp
autorestart=true

[program:xfce]
command=/usr/bin/su - kali -c "DISPLAY=:1 dbus-run-session -- startxfce4"
environment=DISPLAY=":1"
autorestart=true

[program:firefox]
command=/usr/bin/su - kali -c "DISPLAY=:1 firefox-esr --no-remote --profile /home/kali/.mozilla/omnikali"
environment=DISPLAY=":1"
autorestart=true
startsecs=8

[program:x11vnc]
command=/usr/local/bin/omnikali-vnc
autorestart=true

[program:novnc]
command=/usr/bin/websockify --web=/usr/share/novnc 6080 localhost:5900
autorestart=true
