{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-workspace
  namespace: {{ .Values.desktop.namespace }}
  labels:
    omnikali.io/user: {{ .Release.Name | quote }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.desktop.storageClass }}
  resources:
    requests:
      storage: {{ .Values.desktop.storageSize }}
{{- end }}
