{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kali-workspace
  namespace: {{ .Values.desktop.namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.desktop.storageClass }}
  resources:
    requests:
      storage: {{ .Values.desktop.storageSize }}
{{- end }}
