image:
  repository: ghcr.io/onnxscibroccoli/omnikali-kali-desktop
  tag: latest
  pullPolicy: IfNotPresent
desktop:
  namespace: omnikali-desktop
  cpu: "750m"
  memory: 768Mi
  cpuLimit: "1500m"
  memoryLimit: 1536Mi
  serviceType: ClusterIP
  servicePort: 6080
  nodePort: 30080
  storageClass: local-path
  storageSize: 10Gi
  vncSecret: desktop-secret
persistence:
  enabled: true
  accessMode: ReadWriteOnce
security:
  serviceAccountToken: false
  allowPrivilegeEscalation: false
provider:
  name: generic
